// lib/store.ts
export const store = {
    categories: [
      { id: 1, name_gr: "Ορεκτικά", name_en: "Appetizers", sort_order: 1, active: true },
      { id: 2, name_gr: "Σαλάτες", name_en: "Salads", sort_order: 2, active: true },
      { id: 3, name_gr: "Κυρίως Πιάτα", name_en: "Main Courses", sort_order: 3, active: true },
      { id: 4, name_gr: "Επιδόρπια", name_en: "Desserts", sort_order: 4, active: true },
      { id: 5, name_gr: "Ποτά", name_en: "Drinks", sort_order: 5, active: true },
    ],
    subcategories: [
      { id: 1, category_id: 1, name_gr: "Κρύα Ορεκτικά", name_en: "Cold Appetizers", sort_order: 1, active: true },
      { id: 2, category_id: 1, name_gr: "Ζεστά Ορεκτικά", name_en: "Hot Appetizers", sort_order: 2, active: true },
      { id: 3, category_id: 2, name_gr: "Χωριάτικες Σαλάτες", name_en: "Greek Salads", sort_order: 1, active: true },
      { id: 4, category_id: 2, name_gr: "Πράσινες Σαλάτες", name_en: "Green Salads", sort_order: 2, active: true },
      { id: 5, category_id: 3, name_gr: "Κρεατικά", name_en: "Meat Dishes", sort_order: 1, active: true },
      { id: 6, category_id: 3, name_gr: "Θαλασσινά", name_en: "Seafood", sort_order: 2, active: true },
      { id: 7, category_id: 4, name_gr: "Γλυκά", name_en: "Sweets", sort_order: 1, active: true },
      { id: 8, category_id: 4, name_gr: "Παγωτά", name_en: "Ice Creams", sort_order: 2, active: true },
      { id: 9, category_id: 5, name_gr: "Αναψυκτικά", name_en: "Soft Drinks", sort_order: 1, active: true },
      { id: 10, category_id: 5, name_gr: "Μπύρες", name_en: "Beers", sort_order: 2, active: true },
    ],
    products: [
      {
        id: 1,
        category_id: 1,
        subcategory_id: 1,
        name_gr: "Τζατζίκι",
        name_en: "Tzatziki",
        description_gr: "Παραδοσιακό τζατζίκι με αγγούρι και σκόρδο",
        description_en: "Traditional tzatziki with cucumber and garlic",
        price_value: 4.5,
        price_value2: null,
        price_unit: null,
        winery_gr: null,
        winery_en: null,
        is_frozen: false,
        special_order: false,
        sort_order: 1,
        active: true,
      },
      {
        id: 2,
        category_id: 1,
        subcategory_id: 1,
        name_gr: "Τυροκαυτερή",
        name_en: "Tyrokafteri",
        description_gr: "Πικάντικη τυροκαυτερή με φέτα και πιπεριές",
        description_en: "Spicy tyrokafteri with feta cheese and peppers",
        price_value: 5.0,
        price_value2: null,
        price_unit: null,
        winery_gr: null,
        winery_en: null,
        is_frozen: false,
        special_order: false,
        sort_order: 2,
        active: true,
      },
      {
        id: 3,
        category_id: 2,
        subcategory_id: 3,
        name_gr: "Χωριάτικη Σαλάτα",
        name_en: "Greek Salad",
        description_gr: "Κλασική χωριάτικη σαλάτα με ντομάτα, αγγούρι, κρεμμύδι, ελιές και φέτα",
        description_en: "Classic Greek salad with tomato, cucumber, onion, olives and feta cheese",
        price_value: 7.0,
        price_value2: null,
        price_unit: null,
        winery_gr: null,
        winery_en: null,
        is_frozen: false,
        special_order: false,
        sort_order: 1,
        active: true,
      },
      {
        id: 4,
        category_id: 3,
        subcategory_id: 5,
        name_gr: "Μπιφτέκια",
        name_en: "Beef Burgers",
        description_gr: "Ζουμερά μπιφτέκια από φρέσκο κιμά",
        description_en: "Juicy beef burgers from fresh minced meat",
        price_value: 9.5,
        price_value2: null,
        price_unit: null,
        winery_gr: null,
        winery_en: null,
        is_frozen: false,
        special_order: false,
        sort_order: 1,
        active: true,
      },
      {
        id: 5,
        category_id: 4,
        subcategory_id: 7,
        name_gr: "Μπακλαβάς",
        name_en: "Baklava",
        description_gr: "Παραδοσιακός μπακλαβάς με φύλλο και μέλι",
        description_en: "Traditional baklava with phyllo and honey",
        price_value: 6.0,
        price_value2: null,
        price_unit: null,
        winery_gr: null,
        winery_en: null,
        is_frozen: false,
        special_order: false,
        sort_order: 1,
        active: true,
      },
    ],
    settings: [
      { key: "restaurant_name_gr", value: "Το Νότιας" },
      { key: "restaurant_name_en", value: "Notias Restaurant" },
      { key: "delivery_cost", value: "2.5" },
    ],
  }